log_file: C:/Users/nipper/Logs/dev/radiologik_sched_keep_alive.log
wp_endpoint: https://wpdev3.concertzender.nl/wp-admin/admin-ajax.php
email_from: cz.teamservice@gmail.com
email_to_A: lcavdakker@gmail.com
email_to_B: sem@concertzender.nl
email_auth_path: cz-studiomails.json
log_slug: rls_ka
keep_alive_log_uzm: //UITZENDMAC-2/macOS/Users/tech_1/Documents/Salsa/scripts/logs
